### Variables Production
@baseUrl = https://backend-taxi-e2lz.onrender.com/api
@contentType = application/json

### Test estimation Djerba-Tataouine
GET {{baseUrl}}/prix/estimation
    ?depart=djerba
    &arrivee=tataouine
    &passagers=2
    &options=climatisation
Content-Type: {{contentType}}

### Test avec plus de passagers
GET {{baseUrl}}/prix/estimation
    ?depart=djerba
    &arrivee=tataouine
    &passagers=5
    &options=climatisation
Content-Type: {{contentType}}

### Test sans climatisation
GET {{baseUrl}}/prix/estimation
    ?depart=djerba
    &arrivee=tataouine
    &passagers=2
Content-Type: {{contentType}}

### Test calcul distance seule
GET {{baseUrl}}/distance/calculate
    ?originLat=33.8075
    &originLng=10.8451
    &destLat=32.9297
    &destLng=10.4518
Content-Type: {{contentType}} 