### Variables Production
@baseUrl = http://localhost:3002/api
@contentType = application/json

### 1. Test simple estimation prix
GET {{baseUrl}}/prix/estimation
    ?depart=tunis
    &arrivee=sousse
    &passagers=2
    &options=climatisation
Content-Type: {{contentType}}

### 2. Test avec plus de passagers
GET {{baseUrl}}/prix/estimation
    ?depart=tunis
    &arrivee=sousse
    &passagers=5
    &options=climatisation
Content-Type: {{contentType}}

### 3. Test sans climatisation
GET {{baseUrl}}/prix/estimation
    ?depart=tunis
    &arrivee=sousse
    &passagers=2
Content-Type: {{contentType}}

### 4. Test avec ville inconnue
GET {{baseUrl}}/prix/estimation
    ?depart=villeinconnue
    &arrivee=sousse
    &passagers=2
Content-Type: {{contentType}}

### 5. Test détaillé avec logs
GET {{baseUrl}}/prix/estimation
    ?depart=tunis
    &arrivee=sousse
    &passagers=2
    &options=climatisation
    &debug=true
Content-Type: {{contentType}}

### 6. Test calcul distance seule
GET {{baseUrl}}/distance/calculate
    ?originLat=36.8065
    &originLng=10.1815
    &destLat=35.8245
    &destLng=10.6346
Content-Type: {{contentType}} 